version: 0.2

env:
  variables:
    S3_BUCKET: "teal-prebid-js"
    OUTPUT_DIR: "output"

phases:
  pre_build:
    commands:
      - set -e
      - echo "Preparing build..."
      - mkdir -p $OUTPUT_DIR

      - echo "Reading publisher build configuration..."
      - PUBLISHERS=$(jq -c '.publishers[]' .teal/config.json)

      - echo "Installing Gulp CLI and npm dependencies..."
      - npm install -g gulp-cli
      - npm ci

  build:
    commands:
      - set -e
      - echo "Starting multi-publisher build..."
      - |
        for publisher in $PUBLISHERS; do
          NAME=$(echo $publisher | jq -r ".name")
          VERSION=$(echo $publisher | jq -r ".version")
          MODULES=$(echo $publisher | jq -r ".modules | join(\",\")")
          
          echo "Building $NAME from version $VERSION with modules: $MODULES"
          git checkout $VERSION
          gulp build --enable GREEDY --modules="$MODULES"
          cp build/dist/prebid.js $OUTPUT_DIR/${NAME}.js
        done
  post_build:
    commands:
      - set -e
      - echo "Deploying built files to S3..."
      - aws s3 cp $OUTPUT_DIR/ s3://$S3_BUCKET/ --recursive